version: 2.1
orbs:
  nx: nrwl/nx@1.6.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas
      - run:
          command: yarn nx affected -t deploy --base=$NX_BASE --head=$NX_HEAD
          name: Deploy applications
